apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foo
spec:
  destination:
    name: ''
    namespace: sor
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.cloudbees.com/private/product-hub'
    targetRevision: '1.3589'
    chart: sor
    helm:
      parameters:
        - name: sorpostgresql.enabled
          value: 'false'
        - name: sorpostgresql.postgresqlHost
          value: '10.58.32.3'
        - name: sorpostgresql.postgresqlUsername
          value: sor
        - name: sorpostgresql.postgresqlPassword
          value: sor
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
